//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoberturaCoverageReportBaseDirFixer.Core.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoberturaCoverageReportBaseDirFixer.Core.UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;coverage line-rate=&quot;0.97560975609756095&quot; branch-rate=&quot;0&quot; complexity=&quot;0&quot; branches-covered=&quot;0&quot; branches-valid=&quot;0&quot; timestamp=&quot;0&quot; lines-covered=&quot;40&quot; lines-valid=&quot;41&quot; version=&quot;0&quot;&gt;
        ///  &lt;sources&gt;
        ///    &lt;source&gt;c:&lt;/source&gt;
        ///  &lt;/sources&gt;
        ///  &lt;packages&gt;
        ///    &lt;package name=&quot;C:\SandBox\UnitTestFrameworkEvaluation\Debug\ExampleCode.MSTests.dll&quot; line-rate=&quot;0.97560975609756095&quot; branch-rate=&quot;0&quot; complexity=&quot;0&quot;&gt;
        ///      &lt;classes&gt;
        ///        &lt;class name=&quot;user.cpp&quot; filename=&quot;sandbox\unittestf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenCppCoverageReport {
            get {
                return ResourceManager.GetString("OpenCppCoverageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;coverage&gt;
        ///  &lt;packages&gt;
        ///    &lt;package&gt;
        ///      &lt;classes&gt;
        ///        &lt;class name=&quot;user.cpp&quot; filename=&quot;sandbox\unittestframeworkevaluation\examplecode\user.cpp&quot; /&gt;
        ///		&lt;class name=&quot;user2.cpp&quot; filename=&quot;sandbox\unittestframeworkevaluation\examplecode\user2.cpp&quot; /&gt;
        ///	  &lt;/classes&gt;
        ///	&lt;/package&gt;
        ///  &lt;/packages&gt;
        ///&lt;/coverage&gt;.
        /// </summary>
        internal static string VerySimpleReport {
            get {
                return ResourceManager.GetString("VerySimpleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;coverage&gt;
        ///  &lt;packages&gt;
        ///    &lt;package&gt;
        ///      &lt;classes&gt;
        ///        &lt;class name=&quot;user.cpp&quot; filename=&quot;examplecode\user.cpp&quot; /&gt;
        ///		&lt;class name=&quot;user2.cpp&quot; filename=&quot;examplecode\user2.cpp&quot; /&gt;
        ///	  &lt;/classes&gt;
        ///	&lt;/package&gt;
        ///  &lt;/packages&gt;
        ///&lt;/coverage&gt;.
        /// </summary>
        internal static string VerySimpleReportParsed {
            get {
                return ResourceManager.GetString("VerySimpleReportParsed", resourceCulture);
            }
        }
    }
}
